# Workflow to test the React Web App
name: CI - React Web App Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout source repository
        uses: actions/checkout@v3
      # https://github.com/actions/setup-node
      - name: Setup Node.js installation
        uses: actions/setup-node@v3
        with:
          # update the Node version to meet your needs
          node-version: 16
          cache: npm
        working-directory: frontend/algam
      - name: Install Dependencies
        run: |
          cd frontend/algam
          npm ci
      - name: Build Next App
        run: |
          cd frontend/algam
          npm run build