name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd algamlib
          pip install -qr requirements.txt
          pip install .

      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          cd algamlib
          pip install -qr requirements-test.txt
          pytest tests/*.py
